import { Lato } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <header>
          <Link href="/">
            <img
              src="https://upvxroox3cbu7snu.public.blob.vercel-storage.com/logo.jpg"
              alt="Logo"
            />
          </Link>
          <ul>
            <li>
              <a href="/dekoracje">dekoracje</a>
            </li>
            <li>
              <a href="/cechy">cechy</a>
            </li>
            <li>
              <a href="/przewagi">przewagi</a>
            </li>
            <li>
              <a href="/typy">typy</a>
            </li>
          </ul>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
