import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";


const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        <main style={{padding: 20}}>{children}</main>
      </body>
    </html>
  );
}
